# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey",
                    models.IntegerField(
                        choices=[
                            (1, "Afecta mi translado"),
                            (2, "Afecta mi patrimonio"),
                            (3, "Afecta mis labores domesticos"),
                            (4, "Otro"),
                        ],
                        default=1,
                        verbose_name="encuesta",
                    ),
                ),
                ("other", models.TextField(blank=True, null=True, verbose_name="Otra")),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Nombre de la obra"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image8",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image9",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image10",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image11",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image12",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image13",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image14",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image15",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image16",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image17",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image18",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image19",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "image20",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="galery/%Y-%m-%d/",
                        verbose_name="galeria",
                    ),
                ),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name="precio"),
                ),
                (
                    "traffic_light",
                    models.IntegerField(
                        choices=[(1, "Rojo"), (2, "Amarillo"), (3, "Verde")],
                        default=2,
                        verbose_name="semaforo",
                    ),
                ),
                (
                    "official",
                    models.CharField(max_length=200, verbose_name="funcionario"),
                ),
                (
                    "dependence",
                    models.CharField(max_length=500, verbose_name="dependencia"),
                ),
                (
                    "constructor",
                    models.CharField(max_length=200, verbose_name="constructoras"),
                ),
                (
                    "constructor1",
                    models.CharField(max_length=200, verbose_name="constructoras"),
                ),
                (
                    "constructor2",
                    models.CharField(max_length=200, verbose_name="constructoras"),
                ),
                (
                    "constructor3",
                    models.CharField(max_length=200, verbose_name="constructoras"),
                ),
                (
                    "constructor4",
                    models.CharField(max_length=200, verbose_name="constructoras"),
                ),
                (
                    "contracts",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts8",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts9",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts10",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts11",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts12",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts13",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts14",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts15",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts16",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts17",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts18",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts19",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts20",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts21",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts22",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts23",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts24",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts25",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts26",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts27",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts28",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts29",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts30",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts31",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts32",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts33",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts34",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts35",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts36",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts37",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts38",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts39",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts40",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts41",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts42",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts43",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts44",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts45",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts46",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts47",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts48",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts49",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
                (
                    "contracts50",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y-%m-%d/",
                        verbose_name="contratos y licitaciones",
                    ),
                ),
            ],
        ),
    ]
