# Generated by Django 4.1.1 on 2023-04-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='completate',
            field=models.BooleanField(blank=True, null=True, verbose_name='obra completada'),
        ),
    ]
