# Generated by Django 4.1.1 on 2023-04-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_newsletter_delete_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='other',
        ),
    ]
