# Generated by Django 4.1.1 on 2023-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_work_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='completate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='obra completada'),
        ),
    ]
