# Generated by Django 4.1.1 on 2023-04-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_work_completate'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='term2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='días restantes'),
        ),
    ]
