# Generated by Django 4.1.1 on 2023-04-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_work_term2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
