# Generated by Django 4.1.1 on 2023-01-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_work_budget_work_start_of_work_work_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='constructor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='constructoras'),
        ),
        migrations.AlterField(
            model_name='work',
            name='constructor1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='constructoras'),
        ),
        migrations.AlterField(
            model_name='work',
            name='constructor2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='constructoras'),
        ),
        migrations.AlterField(
            model_name='work',
            name='constructor3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='constructoras'),
        ),
        migrations.AlterField(
            model_name='work',
            name='constructor4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='constructoras'),
        ),
        migrations.AlterField(
            model_name='work',
            name='dependence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='dependencia'),
        ),
        migrations.AlterField(
            model_name='work',
            name='official',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='funcionario'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_of_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio de obra'),
        ),
        migrations.AlterField(
            model_name='work',
            name='term',
            field=models.DateTimeField(blank=True, null=True, verbose_name='plazo'),
        ),
    ]
