# Generated by Django 4.1.1 on 2023-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_work_survey_delete_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='work',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Link2'),
        ),
        migrations.AddField(
            model_name='work',
            name='link3',
            field=models.URLField(blank=True, null=True, verbose_name='Link3'),
        ),
        migrations.AddField(
            model_name='work',
            name='link4',
            field=models.URLField(blank=True, null=True, verbose_name='Link4'),
        ),
        migrations.AddField(
            model_name='work',
            name='link5',
            field=models.URLField(blank=True, null=True, verbose_name='Link5'),
        ),
        migrations.AddField(
            model_name='work',
            name='money_used',
            field=models.FloatField(blank=True, null=True, verbose_name='Dinero utilizado'),
        ),
    ]
