# Generated by Django 4.1.1 on 2023-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_work_no_contract_work_no_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='entrepreneur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='orden de gobierno'),
        ),
        migrations.AddField(
            model_name='work',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='REPRESENTANTE LEGAL'),
        ),
        migrations.AddField(
            model_name='work',
            name='signing_of_contract',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Firma de contrato'),
        ),
    ]
