# Generated by Django 4.1.1 on 2023-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_work_entrepreneur_work_legal_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order_gob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='orden de gobierno'),
        ),
        migrations.AlterField(
            model_name='work',
            name='entrepreneur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresario'),
        ),
    ]
