# Generated by Django 4.1.1 on 2023-07-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_work_order_gob_alter_work_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='type_work',
            field=models.IntegerField(choices=[(1, 'Parque'), (2, 'Calle'), (3, 'Cruce'), (4, 'Construccion'), (5, 'Monumento'), (6, 'Activacion')], default=1, verbose_name='Tipo de obra'),
        ),
    ]
