# Generated by Django 4.1.1 on 2023-07-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_work_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type_work',
            field=models.IntegerField(choices=[(1, 'Carretera'), (2, 'Alcantarilla'), (3, 'Tubería'), (4, 'Parque'), (5, 'Competidor'), (6, 'Agua'), (7, 'Edificio')], default=1, verbose_name='Tipo de obra'),
        ),
    ]
