# Generated by Django 4.1.1 on 2023-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_alter_work_type_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='contracts',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts1',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts10',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts11',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts12',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts13',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts14',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts15',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts16',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts17',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts18',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts19',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts2',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts20',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts21',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts22',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts23',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts24',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts25',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts26',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts27',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts28',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts29',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts3',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts30',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts31',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts32',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts33',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts34',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts35',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts36',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts37',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts38',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts39',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts4',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts40',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts41',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts42',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts43',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts44',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts45',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts46',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts47',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts48',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts49',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts5',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts50',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts6',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts7',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts8',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
        migrations.AlterField(
            model_name='work',
            name='contracts9',
            field=models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='contratos y licitaciones'),
        ),
    ]
