# Generated by Django 4.1.1 on 2023-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_alter_work_contracts_alter_work_contracts1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Transcurridos'),
        ),
    ]
