# Generated by Django 4.1.1 on 2023-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_alter_work_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='conclution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dia que se termino'),
        ),
    ]
