# Generated by Django 4.1.1 on 2023-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_alter_work_type_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='credits_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Creditos de las imagenes'),
        ),
        migrations.AddField(
            model_name='work',
            name='link_image',
            field=models.URLField(blank=True, null=True, verbose_name='Link de los creditos'),
        ),
    ]
