# Generated by Django 4.1.1 on 2023-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey',
            field=models.IntegerField(choices=[(1, 'Afecta mi translado'), (2, 'Afecta mi patrimonio'), (3, 'Afecta mis labores domésticas'), (4, 'Otro')], default=1, verbose_name='encuesta'),
        ),
    ]
