# Generated by Django 4.1.1 on 2023-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey',
            field=models.IntegerField(choices=[(1, 'Afecta mi traslado'), (2, 'Afecta mi patrimonio'), (3, 'Afecta mis labores domésticas'), (4, 'Otro')], default=1, verbose_name='encuesta'),
        ),
    ]
