# Generated by Django 4.1.1 on 2023-04-25 21:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=140, null=True)),
                ('last_name', models.CharField(blank=True, max_length=140, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portada_user/')),
                ('genders', models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino'), (3, 'Prefiero no decirlo')], default=1, verbose_name='Genero')),
                ('institute', models.IntegerField(choices=[(1, 'Instituto'), (2, 'Organisación'), (3, 'Ningunio')], default=1, verbose_name='Instituto u Organizacion')),
                ('degree_of_studies', models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria'), (3, 'Preparatoria'), (4, 'Universidad'), (5, 'Maestria'), (6, 'Postgrado')], default=1, verbose_name='Grado de estudios')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
    ]
