# Generated by Django 4.1.1 on 2023-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada_user/'),
        ),
    ]
