# Generated by Django 4.1.1 on 2023-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria')),
                ('introduccion', models.TextField(max_length=1500, verbose_name='introducción')),
                ('investigation', models.TextField(max_length=5500, verbose_name='investigación')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
