# Generated by Django 4.1.1 on 2023-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_investigation_appointment_investigation_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='investigation',
        ),
        migrations.AddField(
            model_name='investigation',
            name='seccion1',
            field=models.TextField(default='“I couldn’t see the Black Panther living on a side street in New York,” Lee explained in a Marvel interview. ”I loved the idea of a superhero that lives in Africa.”', max_length=3500, verbose_name='seccion1'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='seccion2',
            field=models.TextField(default='It’s that background that makes T’Challa, aka the Black Panther, unique; he’s not only black, he’s African. His ties to the continent and culture grant him a rich and complex mythology that his American counterparts do not have.', max_length=3500, verbose_name='seccion2'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='seccion3',
            field=models.TextField(default='Afrocentrism defines every part of his character, beginning with his name. There’s the literal definition. Black panthers, the great cats native to Africa, serve as a motif for T’Challa’s superhero persona. Then there’s the fictional definition', max_length=3500, verbose_name='seccion3'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='seccion4',
            field=models.TextField(default='The Black Panther is a title given to each chieftain of the Panther Clan of Wakanda, the nation that T’Challa rules.<br><br> In the new Black Panther feature film, Afrocentrism and Afrofuturism – the interpretation of African traditions into', max_length=3500, verbose_name='seccion4'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='seccion5',
            field=models.TextField(default='their futuristic possibilities – combine to create an aesthetic never before seen in the Marvel Cinematic Universe.<br><br> With the Black Panther in theaters, we examine how Afrocentrism and Afrofuturism inform Wakanda, its leader, and it citizens.', max_length=3500, verbose_name='seccion5'),
        ),
    ]
