# Generated by Django 4.1.1 on 2023-09-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0003_remove_investigation_investigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
