# Generated by Django 4.1.1 on 2023-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0006_investigation_seccion6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='credit',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Creditos'),
        ),
    ]
