# Generated by Django 4.1.1 on 2023-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0007_investigation_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='credit',
            field=models.TextField(blank=True, max_length=4500, null=True, verbose_name='Creditos'),
        ),
    ]
