# Generated by Django 4.1.1 on 2023-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0008_alter_investigation_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='by',
            field=models.CharField(default='Aqui se construye', max_length=800, verbose_name='Escrito por'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='credit',
            field=models.TextField(blank=True, max_length=5500, null=True, verbose_name='Creditos'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion1',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion1'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion2',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion2'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion3',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion3'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion4',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion4'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion5',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion5'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='seccion6',
            field=models.TextField(blank=True, max_length=6500, null=True, verbose_name='seccion6'),
        ),
    ]
