# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Whoweare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "who_we_are",
                    models.TextField(
                        blank=True, null=True, verbose_name="quienes somos"
                    ),
                ),
            ],
        ),
    ]
