# Generated by Django 4.1.1 on 2023-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria'),
        ),
    ]
