# Generated by Django 4.1.1 on 2023-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_whoweare_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroAquiSeConstruye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='quienes somos')),
            ],
        ),
    ]
