# Generated by Django 4.1.1 on 2023-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_introaquiseconstruye'),
    ]

    operations = [
        migrations.AddField(
            model_name='introaquiseconstruye',
            name='metodologic',
            field=models.TextField(blank=True, null=True, verbose_name='Metodo'),
        ),
    ]
