# Generated by Django 4.1.1 on 2023-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_introaquiseconstruye_metodologic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodologic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologic', models.TextField(blank=True, null=True, verbose_name='Metodo')),
            ],
        ),
        migrations.RemoveField(
            model_name='introaquiseconstruye',
            name='metodologic',
        ),
    ]
