# Generated by Django 4.1.1 on 2023-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_introaquiseconstruye_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria'),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='inv', verbose_name='galeria'),
        ),
    ]
