# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="user-icon.png", upload_to="")),
                (
                    "genders",
                    models.IntegerField(
                        choices=[
                            (1, "Femenino"),
                            (2, "Masculino"),
                            (3, "Prefiero no decirlo"),
                        ],
                        default=1,
                        verbose_name="Genero",
                    ),
                ),
                (
                    "institute",
                    models.IntegerField(
                        choices=[
                            (1, "Instituto"),
                            (2, "Organisación"),
                            (3, "Ningunio"),
                        ],
                        default=1,
                        verbose_name="Instituto u Organizacion",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Nombre")),
                (
                    "degree_of_studies",
                    models.IntegerField(
                        choices=[
                            (1, "Primaria"),
                            (2, "Secundaria"),
                            (3, "Preparatoria"),
                            (4, "Universidad"),
                            (5, "Maestria"),
                            (6, "Postgrado"),
                        ],
                        default=1,
                        verbose_name="Grado de estudios",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
    ]
